### ISSUE TITLE
appli minimale carteconsoplus

### ISSUE THREAD

**Issue by meilie389** [adriens/GLIA-tasks#12]
- [x] [Ecran qui liste les Partenaires](https://github.com/adriens/carte-conso-plus-appli/issues/1)
- [x] [Créer un logo](https://github.com/adriens/carte-conso-plus-appli/issues/2)
- [x] [Splashscreen](https://github.com/adriens/carte-conso-plus-appli/issues/3)
- [x] [Authentification (sans enregistrer les credentials) et écran solde/points](https://github.com/adriens/carte-conso-plus-appli/issues/4)

**Comment by adriens** [comment]
ca avnce bien c cool !
